# Generated by Django 3.0.4 on 2020-05-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200529_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Meetings'},
        ),
    ]
